# Generated by Django 2.0.2 on 2019-02-22 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetName', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=10)),
                ('assetType', models.CharField(max_length=100)),
                ('addedOn', models.DateTimeField(default=datetime.datetime(2019, 2, 22, 17, 16, 17, 992616))),
                ('addedBy', models.CharField(default='User_0001', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('assetType', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('extName', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tagName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(to='Assets.Tags'),
        ),
    ]
